paths:
  diffusion: "/root/autodl-tmp/multipoly/exp/exp_v3/ckpts/best.pth"
  chord_condition:
  output_folder:



models:
  transformers:
    n_intertrack_head: 4
    num_intertrack_encoder_layers: 1
    intertrack_attention_levels:
    - 2
    - 3
