paths:
  diffusion: "/root/autodl-tmp/multipoly/exp/exp_v3_v1/ckpts/best.pth"
  cond: "/root/autodl-tmp/multipoly/data/val_segs/seg_20939.mid"
  output: "/root/autodl-tmp/multipoly/exp/exp_v3_v1/output/"
 
models:
  transformers:
    n_intertrack_head: 4
    num_intertrack_encoder_layers: 1
    intertrack_attention_levels:
    - 2
    - 3

samples:
  num_gen: 5
  temperature: 1.0



  

  
