paths:
  polyffusion: "/root/autodl-tmp/multipoly/polyffusion_ckpts/ldm_chd8bar/sdf+pop909wm_mix16_chd8bar/01-11_102022/chkpts/weights_best.pt"
  chord_encoder: "/root/autodl-tmp/multipoly/pretrained/chd8bar/weights.pt"
  dataset: "/root/autodl-tmp/multipoly/data/lmd/lpd_filtered_2"
  output: "./exp/exp_v2"

data:
  batch_size: 7
  num_workers: 0
  train_ratio: 0.9

init:
  intertrack: "random"
  intratrack: "random"

models:
  transformers:
    n_intertrack_head: 4
    num_intertrack_encoder_layers: 1
    intertrack_attention_levels:
    - 2
    - 3


training:
  freeze_polyffusion: true
  optim: "adam"
  lr: 5.0e-5
  accumulation_steps: 50
  



  

  
