paths:
  polyffusion: "/root/autodl-tmp/multipoly/polyffusion_ckpts/ldm_chd8bar/sdf+pop909wm_mix16_chd8bar/01-11_102022/chkpts/weights_best.pt"
  chord_encoder: "/root/autodl-tmp/multipoly/pretrained/chd8bar/weights.pt"
  train_folder: "/root/autodl-tmp/multipoly/data/train"
  val_folder: "/root/autodl-tmp/multipoly/data/val"
  output: "/root/autodl-tmp/multipoly/exp/exp_v4"

data:
  train_bs: 6
  val_bs: 7
  num_workers: 8
  

init:
  intertrack: "zero"
  intratrack: "polyffusion"

models:
  transformers:
    n_intertrack_head: 4
    num_intertrack_encoder_layers: 1
    intertrack_attention_levels:
    - 

  use_conv3d: True


training:
  freeze_polyffusion: false
  optim: "adam"
  lr: 1.0e-4
  accumulation_steps: 15
  warmup_steps: 600
  decay_factor: 0.2
  decay_interval: 40000
  log_train_loss_interval: 100
  validation_interval: 1000

  generate_chord_conditioned_samples_interval: 200000
  generate_track_conditioned_samples_interval: 200000

validation:
  num_seg: 2
  num_gen_per_seg: 1
  



  

  
