paths:
  diffusion: /root/autodl-tmp/multipoly/exp/exp_v4/ckpts/best.pth
  cond: /root/autodl-tmp/multipoly/data/fushi.mid
  output: /root/autodl-tmp/multipoly/exp/exp_v4/whole_song/

models:
  transformers:
    n_intertrack_head: 4
    num_intertrack_encoder_layers: 1
    intertrack_attention_levels:
      -
      
  use_conv3d: True

samples:
  num_gen: 1
  temperature: 1.0
  chord_scales:
    - 0.5
    - 0.75
    - 1.0
  paint_scales:
    - 0.5
    - 0.75
    - 1.0
