paths:
  diffusion: "C:\\Users\\19941\\Desktop\\meeting\\exp\\ckpts\\best.pth"
  cond: "C:\\Courses\\S6\\multipoly\\data\\lpd_5_midi\\293.mid"
  output: "./exp/exp_v3_v1/whole_song/"

models:
  transformers:
    n_intertrack_head: 4
    num_intertrack_encoder_layers: 1
    intertrack_attention_levels:
      - 2
      - 3

samples:
  num_gen: 1
  temperature: 1.0
  chord_scales:
    - 0.5
    - 0.75
    - 1.0
  paint_scales:
    - 0.5
    - 0.75
    - 1.0
